# Development Bundle - Software Development Workflows
# Sprint 95, Feature 95.3: Standard Skill Bundles

id: development_bundle
name: Development Bundle
version: 1.0.0
description: |
  Complete skill bundle for software development workflows including code generation,
  review, testing, and debugging. Supports multiple programming languages and
  development best practices.

# Skills included in bundle
skills:
  - name: code_generation
    version: "^1.0.0"
    required: true
    description: Generate code from specifications
    config:
      languages:
        - python
        - javascript
        - typescript
        - java
        - go
      style: "production"  # production, prototype, minimal
      include_tests: true
      include_docstrings: true
      include_type_hints: true
      max_lines: 500

  - name: code_review
    version: "^1.0.0"
    required: true
    description: Review code for quality and best practices
    config:
      checks:
        - style
        - complexity
        - security
        - performance
        - maintainability
      severity_levels:
        - error
        - warning
        - info
      output_format: "markdown"
      include_suggestions: true

  - name: testing
    version: "^1.0.0"
    required: true
    description: Generate and run tests
    config:
      frameworks:
        python: pytest
        javascript: jest
        typescript: jest
        java: junit
      coverage_threshold: 0.8
      test_types:
        - unit
        - integration
      include_fixtures: true
      include_mocks: true

  - name: debugging
    version: "^1.0.0"
    required: true
    description: Debug and fix code issues
    config:
      trace_depth: 10
      variable_inspection: true
      suggest_fixes: true
      explain_errors: true
      breakpoint_analysis: true

# Bundle configuration
context_budget: 10000  # Large budget for code context
priority: "quality"   # Code quality is critical

# Auto-activation rules
auto_activate:
  - code_review  # Always review generated code
  - testing      # Always include tests

# Natural language triggers
triggers:
  - write code
  - generate function
  - create class
  - review code
  - debug error
  - fix bug
  - write tests
  - refactor code
  - implement feature

# Required permissions
permissions:
  tools:
    - code_execution
    - file_read
    - file_write
    - git_operations
  data:
    - read_codebase
    - write_codebase
  llm:
    - invoke_generation
    - invoke_analysis

# External dependencies
dependencies:
  python:
    - pytest >= 7.4.0
    - mypy >= 1.7.0
    - ruff >= 0.1.0
    - black >= 23.11.0
  system:
    - git >= 2.40.0

# Skill execution order
installation_order:
  - code_generation
  - code_review
  - testing
  - debugging

# Usage examples
usage_examples:
  - query: "Generate a Python function to parse CSV files"
    skills_used: [code_generation, code_review, testing]

  - query: "Review this pull request for security issues"
    skills_used: [code_review, debugging]

  - query: "Debug why this function returns None"
    skills_used: [debugging, code_review]

  - query: "Write unit tests for the UserService class"
    skills_used: [testing, code_generation]

# Performance characteristics
performance:
  avg_latency_ms: 1200
  p95_latency_ms: 2500
  max_concurrent: 2  # Code generation is resource-intensive

# Bundle metadata
metadata:
  category: development
  use_case: software_development
  complexity: high
  maturity: stable
  last_updated: "2026-01-15"
  author: AegisRAG Team
