# Research Bundle - Information Gathering and Retrieval
# Sprint 95, Feature 95.3: Standard Skill Bundles

id: research_bundle
name: Research Bundle
version: 1.0.0
description: |
  Complete skill bundle for research and information gathering workflows.
  Combines web search, knowledge base retrieval, graph traversal, and citation
  management for comprehensive research capabilities.

# Skills included in bundle
skills:
  - name: web_search
    version: "^1.0.0"
    required: true
    description: Search the web for real-time information
    config:
      max_results: 10
      engines:
        - google
        - bing
      timeout_seconds: 30
      enable_caching: true

  - name: retrieval
    version: "^1.0.0"
    required: true
    description: Retrieve documents from vector database
    config:
      top_k: 5
      mode: "hybrid"  # vector + sparse (BGE-M3)
      rerank: true
      rerank_top_k: 3
      min_score: 0.5

  - name: graph_query
    version: "^1.0.0"
    required: true
    description: Query knowledge graph for entity relationships
    config:
      max_hops: 2
      max_entities: 20
      expand_entities: true
      similarity_threshold: 0.7

  - name: citation
    version: "^1.0.0"
    required: true
    description: Generate and format citations
    config:
      style: "APA"
      include_urls: true
      include_page_numbers: true

# Bundle configuration
context_budget: 8000  # Max tokens for all skills combined
priority: "balanced"  # balanced, speed, quality

# Auto-activation rules
auto_activate:
  - retrieval  # Always active for RAG workflows
  - citation   # Always track sources

# Natural language triggers for bundle recommendation
triggers:
  - research
  - find information
  - investigate
  - look up
  - search for
  - gather data
  - fact check
  - verify sources

# Required permissions
permissions:
  tools:
    - browser
    - web_fetch
    - search_api
  data:
    - read_documents
    - read_graph
  llm:
    - invoke_generation
    - invoke_embeddings

# External dependencies
dependencies:
  system:
    - qdrant >= 1.11.0
    - neo4j >= 5.0.0
  python:
    - langchain >= 0.1.0
    - requests >= 2.31.0

# Skill execution order (for sequential workflows)
installation_order:
  - web_search
  - retrieval
  - graph_query
  - citation

# Usage examples
usage_examples:
  - query: "Research the latest advances in quantum computing"
    skills_used: [web_search, retrieval, citation]

  - query: "Find information about Neo4j graph algorithms"
    skills_used: [retrieval, graph_query, citation]

# Performance characteristics
performance:
  avg_latency_ms: 850
  p95_latency_ms: 1500
  max_concurrent: 3

# Bundle metadata
metadata:
  category: research
  use_case: academic_research
  complexity: medium
  maturity: stable
  last_updated: "2026-01-15"
  author: AegisRAG Team
